name: Build

on: [push]

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        timeout-minutes: 5
      - name: 7z
        run: |
          gcm 7z
          Get-Content -Path (gcm 7z).Source
          7z
